### ISSUE TITLE
Required headers are not recognised correctly 

### ISSUE THREAD

**Issue by githubmo** [blinkboxbooks/swaggerific#32]
When sending a header with a HTTP request to swaggerific that is required, you still get an error stating that the required header has not been given even though it has. Example, if we have the following yaml:

``` yaml
paths:
  /special:
    get:
      parameters:
        - name: Authorization
          in: header
          description: The bearer token for Oauth
          type: string
          required: true
          format: "/^Bearer .+/"
```

When you call the endpoint with the following curl command, `curl -H "Authorization: Bearer blahblah" http://special.swaggerific.io/special`, assuming `special` is the subdomain we are using, we would still get the following error message:

``` json
{"error":"missing_params","message":"Required parameters are missing","details":{"reasons":{"Authorization":"is missing"}}}
```
